---

- hosts: all
  become: true
  tasks:

  - name: update repository index
    yum:
      update_cache: yes

  - name: install httpd
    yum:
      name: httpd
      state: absent

  - name: add php support for apache
    yum:
      name: php
      state: absent
