---

- hosts: all
  become: true
  tasks:

  - name: update repository index
    yum:
      update_cache: yes

  - name: install apache2 package
    yum:
      name: apache2
      state: absent

  - name: add php support for apache
    yum:
      name: lipapache2-mod-php
      state: absent
